layout_spectrum: 0.23445773706771433
typography_spectrum: 0.5663768129888922
color:
  brandStrength: 0.8474920382723212
  lightness: 0.371731614228338
  saturation: 0.3332341266795993
  rhythmicContrast: 0.08475546631962061
  brandColors:
    - '#222222'
    - '#A3A3A3'
    - '#5E2727'
    - '#FFFFFF'
coverPrefs:
  filter: false
name: DVSN
navigation:
  - name: DVSN Mag
    url: 'http://www.thestyledivision.com/'
    type: external
title: DVSN
description: Collective
