typography_spectrum: 0.5663768129888922
color:
  brandStrength: 0.22141050198115408
  lightness: 0.937947406899184
  saturation: 0.1642732156906277
  rhythmicContrast: 0.8814275723416358
  brandColors:
    - '#222222'
    - '#A3A3A3'
    - '#5E2727'
    - '#FFFFFF'
layout_spectrum: 0.23445773706771433
name: DVSN
navigation:
  - name: DVSN Mag
    url: 'http://www.thestyledivision.com/'
    type: external
title: DVSN Collective
coverPrefs:
  filter: false
description: ''
