layout_spectrum: 0.6478083173278719
typography_spectrum: 0.9533009305596352
color:
  brandColors:
    - '#222222'
    - '#A3A3A3'
    - '#5E2727'
    - '#FFFFFF'
  brandStrength: 0.026499659288674593
  lightness: 0.711806058883667
  saturation: 0.6169003508985043
  rhythmicContrast: 0.8592463175300509
coverPrefs:
  filter: false
analytics:
  facebook: ''
  google: UA-30551785-1
  twitter: ''
name: DVSN
navigation:
  - name: DVSN Mag
    url: 'http://www.thestyledivision.com/'
    type: external
  - name: Creative DVSN
    url: 'http://www.thestyledivision.com/visual-creative-journal'
    type: external
title: DVSN Collective
