layout_spectrum: 0.9812845424748957
typography_spectrum: 0.5599166853353381
color:
  brandColors:
    - '#222222'
    - '#A3A3A3'
    - '#5E2727'
    - '#FFFFFF'
  brandStrength: 0.026499659288674593
  lightness: 0.711806058883667
  saturation: 0.6169003508985043
  rhythmicContrast: 0.8592463175300509
coverPrefs:
  filter: false
name: DVSN
analytics:
  facebook: ''
  google: UA-30551785-1
  twitter: ''
title: DVSN Collective
navigation:
  - name: DVSN Mag
    url: 'http://www.thestyledivision.com/'
    type: external
